### ISSUE TITLE
I can't run it on local

### ISSUE THREAD

**Issue by DawnyWu** [wrobin/favesound-redux#1]
![image](https://cloud.githubusercontent.com/assets/949508/14420195/2b1802d0-fffd-11e5-8058-637e5306acfd.png)

I've got my client id and edit authentification.js file
npm start tells me `can't get /`

**Comment by rwieruch** [comment]
@DawnyWu can you follow the install steps again with a fresh clone? I forgot to commit a file. It should work now.

**Comment by rwieruch** [comment]
@DawnyWu Make sure you use http://localhost:8080/callback as Redirect URI in your soundcloud app.

**Comment by DawnyWu** [comment]
It works!!! 😄  Thank you
