### ISSUE TITLE
Fixing react-hot-loader

### ISSUE THREAD

**Issue by chriszhangusc** [wrobin/favesound-redux#101]
Should we remove react-hot-loader because it states if we use babel we do not need it [here](https://github.com/gaearon/react-hot-loader#using-webpack-loader-instead-of-babel-plugin)?

**Comment by rwieruch** [comment]
If it doesn't add any value, removing it sounds reasonable! 👍

**Comment by chriszhangusc** [comment]
I made a mistake here. It is not set up properly so I thought it is not working. I'll create a PR to fix it.

**Comment by chriszhangusc** [comment]
Merged #102
