### ISSUE TITLE
Add a link to dashboard

### ISSUE THREAD

**Issue by chriszhangusc** [wrobin/favesound-redux#103]
There should be a link for the signed in user to access the dashboard page instead of having to type in url.

**Comment by rwieruch** [comment]
Good point!

**Comment by ElishebaW** [comment]
@rwieruch I'll take this one!

**Comment by ElishebaW** [comment]
@rwieruch I'll take this one!

**Comment by rwieruch** [comment]
Sounds good @ElishebaW 🎉

**Comment by ElishebaW** [comment]
Hey @rwieruch , this issue can be closed :)
