### ISSUE TITLE
Strange characters appear between artist and track name in Safari 11.0.2

### ISSUE THREAD

**Issue by erikmartinessanches** [wrobin/favesound-redux#106]
![screenshot 2017-12-29_05-18-30](https://user-images.githubusercontent.com/4912935/34429383-de7dcc0e-ec57-11e7-9ef9-20e8ac262338.png)
The actual [track](https://soundcloud.com/keeganthedeadbeat/flight-risk).

**Comment by rwieruch** [comment]
Oh. I didn't know this. Maybe a good first time contributor issue?

**Comment by ElishebaW** [comment]
I'll take this one!
