### ISSUE TITLE
Impossible to type upper case letters in the search box.

### ISSUE THREAD

**Issue by erikmartinessanches** [wrobin/favesound-redux#108]

**Comment by rwieruch** [comment]
I think this is fine, because everything is lower cased (search term and titles of tracks).

**Comment by erikmartinessanches** [comment]
Track and artist names appear mixed case to me on Safari. 
![screenshot 2017-12-29_08-51-31](https://user-images.githubusercontent.com/4912935/34432201-92d67ba2-ec75-11e7-8039-7c4d4abc345e.png) Allowing mixed case in the search bar would be more conventional. I've never encountered this situation and found myself double checking whether I pressed shift. A minor annoyance but worth considering.

**Comment by rwieruch** [comment]
Ah okay. Seems like a good improvement! :)
