### ISSUE TITLE
Playlist icon does not display right in firefox

### ISSUE THREAD

**Issue by chriszhangusc** [wrobin/favesound-redux#20]
Firefox version: 51.0.1
In firebox: 
<img width="91" alt="screen shot 2017-02-15 at 10 15 21 pm" src="https://cloud.githubusercontent.com/assets/15867071/23009700/42c66d2c-f3cc-11e6-86c3-1a387c0d954e.png">

It should be like: 
<img width="114" alt="screen shot 2017-02-15 at 10 14 46 pm" src="https://cloud.githubusercontent.com/assets/15867071/23009679/2e3806c2-f3cc-11e6-8b0c-bbf6d3ed4d55.png">

**Comment by rwieruch** [comment]
Oh damn @MiniPekka , I didn't notice that. Would you take care of it? :)

**Comment by rwieruch** [comment]
https://github.com/rwieruch/favesound-redux/pull/21
