### ISSUE TITLE
Feature Proposal: Automatically play next song in stream

### ISSUE THREAD

**Issue by kafisher** [wrobin/favesound-redux#27]
Right now only the next song in a playlist will be played automatically, but stops after the playlist finishes. I propose the player should keep always play a continuous stream of music and automatically play the next song in the stream if the playlist finishes or if you didn't create a playlist.

**Comment by rwieruch** [comment]
Sounds great! Would you try to implement it?

**Comment by kafisher** [comment]
Sure I'll get started soon.

**Comment by rwieruch** [comment]
Merged in https://github.com/rwieruch/favesound-redux/pull/50
