### ISSUE TITLE
Feature Proposal: add time passed to nav

### ISSUE THREAD

**Issue by jasonkwong11** [wrobin/favesound-redux#28]
I propose we add a feature to indicate the time passed after a song begins. This would be located in the bottom nav, similar to how SoundCloud handles it:

<img width="539" alt="screen shot 2017-05-23 at 4 26 23 pm" src="https://cloud.githubusercontent.com/assets/17104743/26374808/976b96e6-3fd4-11e7-95f0-4fde2089db92.png">

**Comment by rwieruch** [comment]
Sounds pretty cool! Would you go for it?

**Comment by jasonkwong11** [comment]
Sure!

**Comment by rwieruch** [comment]
Added by @jasonkwong11 in https://github.com/rwieruch/favesound-redux/pull/35 🎉
