### ISSUE TITLE
Feature Proposal: Player with Duration Bar

### ISSUE THREAD

**Issue by rwieruch** [wrobin/favesound-redux#3]
At this time, once you want to listen to a track, you only get to see a backward, a play/pause and a forward button in the player. 

<img width="566" alt="screen shot 2016-07-08 at 17 39 43" src="https://cloud.githubusercontent.com/assets/2479967/16692967/656df554-4533-11e6-8349-423c813303c2.png">

But most of the audio player come with a progress bar and a current time to indicate the playback time duration.

<img width="892" alt="screen shot 2016-07-09 at 12 45 29" src="https://cloud.githubusercontent.com/assets/2479967/16707552/11b7d1b4-45d3-11e6-98fd-5a8cd306db5c.png">

It would be cool to have something like this for FaveSound as well! One could implement it in different ways. Either you use a stateful component within the player which keeps _track_ of the duration time of the track or you save that state to the global redux state. I would recommend to do the former, otherwise you will end up with a lot recurring actions (like every 5 seconds?).

**Comment by C-Rodg** [comment]
I've created a simple duration bar for the application. PR #15

**Comment by rwieruch** [comment]
Such a great addition, thanks @C-Rodg 👍

**Comment by konamax123** [comment]
Hey, just pulled down this repo but I do not see this implementation in the player. Any reason why not?
