### ISSUE TITLE
Bug: Volume Slider doesn't close

### ISSUE THREAD

**Issue by rwieruch** [wrobin/favesound-redux#30]
The Volume Slider that is attached to the Player in the bottom doesn't close when the Player closes. However, that should be the case. It should be the same as the Playlist that is attached to the Player  which disappears when the Player disappears.

<img width="1413" alt="screen shot 2017-05-26 at 10 29 22" src="https://cloud.githubusercontent.com/assets/2479967/26487286/2dfc7b58-41ff-11e7-9fb9-a314057e16cc.png">

**Comment by MiniPekka** [comment]
How to close the player?  I can not reproduce this error lol.

**Comment by rwieruch** [comment]
Fixed in https://github.com/rwieruch/favesound-redux/pull/39 by @MiniPekka 🎉
