### ISSUE TITLE
Bug: Volume Slider shows String

### ISSUE THREAD

**Issue by rwieruch** [wrobin/favesound-redux#31]
There is an UI glitch where the Volume Slider shows the value of the volume somewhere in between. 
<img width="108" alt="screen shot 2017-05-26 at 10 29 16" src="https://cloud.githubusercontent.com/assets/2479967/26487321/543c6b98-41ff-11e7-938d-c46e76c49ed2.png">

**Comment by prasim** [comment]
https://github.com/rwieruch/favesound-redux/pull/33

**Comment by rwieruch** [comment]
Thank you very much! 👍
