### ISSUE TITLE
Errors: A bunch of errors caused by Waveform

### ISSUE THREAD

**Issue by chriszhangusc** [wrobin/favesound-redux#36]
<img width="752" alt="favesound_waveform" src="https://cloud.githubusercontent.com/assets/15867071/26829347/13617a22-4a7a-11e7-9fc7-5f75d313878f.png">
This happened when I first loaded the app, I tried to remove the WaveformSc component from stream.js and the errors disappeared. I will look into this later today.

**Comment by rwieruch** [comment]
Yes. I guess SoundCloud changed something when you are not logged in. When you log in, I think it might work. But still would be good to investigate this issue, thanks!

**Comment by chriszhangusc** [comment]
I looked into the issue and found that SoundCloud API v1 will give you PNG while V2 will give you JSON, I tried JSON and everything was alright. So the problem is with PNG not JSON. If that is the case, we can either write a backend proxy API to call SoundCloud API v2 for us since we can not directly call SC API v2 from the browser.

**Comment by rwieruch** [comment]
@MiniPekka Ah, I remember at least that there was a difference between PNG and JSON formatted waveforms. You can have a look at the `WaveformSc` component that is already able to deal with both representations. 

The rule was: When not logged in, you have a PNG as `waveform_url` in your track entity. When logged in, you have JSON (or it was the other way around). I wasn't aware that SoundCloud changed something around it.

**Comment by chriszhangusc** [comment]
@rwieruch Actually, we can just replace the .png to .json in waveform_url and everything is fine right now. I'll make a pull request fixing this as well as tracks not being able to play issue.

**Comment by rwieruch** [comment]
Fixed in https://github.com/rwieruch/favesound-redux/pull/43 by @MiniPekka 🎉
