### ISSUE TITLE
 Improvements: Automatically login if we have a valid oauth_token in cookie.

### ISSUE THREAD

**Issue by chriszhangusc** [wrobin/favesound-redux#44]
After we successfully login and then close the app without logging out, the oauth_token would still be in the cookie, next time when we visit out app all requests will be made with oauth_token but our app would be in logged out state. 
So should we check if oauth_token is there, if it is, we perform a login and fetch everything related to this user?
Or should we log the user out when we close the app to keep the oauth_token in cookie and our auth state in sync?

**Comment by rwieruch** [comment]
Either way would be ok I guess. Maybe we should logout to keep the complexity low.

**Comment by chriszhangusc** [comment]
OK, I'm on it.
