### ISSUE TITLE
[Minor] Nesting anchor tag warning

### ISSUE THREAD

**Issue by chriszhangusc** [wrobin/favesound-redux#51]
1. When clicking play button, this warning pops up.
<img width="1421" alt="screen shot 2017-06-19 at 5 21 20 pm" src="https://user-images.githubusercontent.com/15867071/27311131-bcb289a6-5513-11e7-89b1-f7c5b8205f61.png">

2. It sometimes appears in a weird position like the following:
<img width="305" alt="screen shot 2017-06-19 at 10 00 25 pm" src="https://user-images.githubusercontent.com/15867071/27317655-a896b2ca-553c-11e7-81ab-6d737977a07b.png">
<img width="189" alt="screen shot 2017-06-19 at 10 00 41 pm" src="https://user-images.githubusercontent.com/15867071/27317656-a89a6848-553c-11e7-94c5-891294075dd2.png">

3. As for now, we have to click the button again to make the tooltip to disappear, IMO, I think it should be automatically hidden after a certain amount of time. 

I'll create a PR tonight to fix these.

**Comment by rwieruch** [comment]
What happened to the PR? :) https://github.com/rwieruch/favesound-redux/pull/52

**Comment by chriszhangusc** [comment]
@rwieruch That one just resolves the first issue, I'll create another one to fix them all at once.

**Comment by rwieruch** [comment]
That one was merged, right?

**Comment by chriszhangusc** [comment]
Yes, it's merged: )
