### ISSUE TITLE
[Bugs] Errors after clicking clear queue in playlist

### ISSUE THREAD

**Issue by chriszhangusc** [wrobin/favesound-redux#55]
<img width="797" alt="screen shot 2017-06-20 at 12 44 09 pm" src="https://user-images.githubusercontent.com/15867071/27352657-551105cc-55b6-11e7-82e7-ba05ff02ecb4.png">

**Comment by rwieruch** [comment]
Oh damn, could this have happened after https://github.com/rwieruch/favesound-redux/pull/50 ? Maybe I need to check again this PR or even revert it.

**Comment by chriszhangusc** [comment]
Let me see if I can fix it later today: )

**Comment by chriszhangusc** [comment]
PR: #56
