### ISSUE TITLE
[Bug] Errors when clicking on genre links

### ISSUE THREAD

**Issue by chriszhangusc** [wrobin/favesound-redux#62]
Screenshot: 
<img width="1895" alt="screen shot 2017-06-21 at 10 40 15 pm" src="https://user-images.githubusercontent.com/15867071/27418882-aff875b6-56d2-11e7-897c-ec5d3017b560.png">

This could be caused by waveform component.

**Comment by rwieruch** [comment]
I assume that was the fix https://github.com/rwieruch/favesound-redux/pull/63 ? 🎉

**Comment by chriszhangusc** [comment]
Yeah they're fixed in PR #63.
