### ISSUE TITLE
[Bug] Favorites long title being squeezed

### ISSUE THREAD

**Issue by chriszhangusc** [wrobin/favesound-redux#64]
<img width="499" alt="screen shot 2017-06-25 at 11 25 25 pm" src="https://user-images.githubusercontent.com/15867071/27526902-b7390394-59fd-11e7-881d-b3b74acf4661.png">

**Comment by rwieruch** [comment]
In this case you mean for the "Priince Muzik"? Yes, I think it happens when people use Emojis. For the "Mixpak - Popcaan" and the hover buttons I think it is fine, since the buttons are not always visible.

**Comment by chriszhangusc** [comment]
Yes, I think the hover buttons are fine. PR: #65
