### ISSUE TITLE
[UI] Tooltips not having enough space to display on top

### ISSUE THREAD

**Issue by chriszhangusc** [wrobin/favesound-redux#67]
When the screen size is small, tooltips will not have enough space to be displayed on top of the button. 
<img width="222" alt="screen shot 2017-06-28 at 1 12 45 am" src="https://user-images.githubusercontent.com/15867071/27626984-f7b09192-5b9e-11e7-9b6c-f543b9e083a2.png">

I tried to adjust the player left and right margin to 10%, it will have enough space to display. However, this will change how the player looks. Any suggestions on this? 
<img width="1134" alt="screen shot 2017-06-28 at 1 18 24 am" src="https://user-images.githubusercontent.com/15867071/27627189-b71092b2-5b9f-11e7-8fe7-19fbd8766ceb.png">

**Comment by rwieruch** [comment]
I guess the player looks alright. Only the title of the track could have some more space and perhaps a bit of margin? 

edit: Okay, I saw that this had nothing to do with your change. It was already before that the title is very squeezed. I would say adjusting the margins is alright! 👍 

<img width="969" alt="screen shot 2017-10-03 at 20 42 26" src="https://user-images.githubusercontent.com/2479967/31128341-bb2b7154-a87b-11e7-9bc8-ccb9bc343235.png">

**Comment by rwieruch** [comment]
@MiniPekka do you still have this change somewhere around? We could merge it in a PR :)

**Comment by chriszhangusc** [comment]
@rwieruch Sure, I'll look into it.
