### ISSUE TITLE
New feature proposal: Repeat button on the navbar

### ISSUE THREAD

**Issue by jasonkwong11** [wrobin/favesound-redux#68]
I think it would be a nice addition to add a button on the nav to repeat the current song, similar to the SoundCloud nav: 
<img width="274" alt="screen shot 2017-07-30 at 9 20 58 pm" src="https://user-images.githubusercontent.com/17104743/28762663-1db314e0-756d-11e7-9a3a-89ff22b1922a.png">

**Comment by rwieruch** [comment]
Sounds great to me :)

**Comment by jasonkwong11** [comment]
Thanks to @gokulchandra and @MiniPekka for completing this. Closed
