### ISSUE TITLE
After logging in it redirects to this page.

### ISSUE THREAD

**Issue by angelom88** [wrobin/favesound-redux#74]
http://www.favesound.de/callback?code=4db5405237b0f7b315c61215d6490189&signed_up=1&state=SoundCloud_Dialog_223b9#access_token=1-231734-339559294-32509ffa28ba1&scope=non-expiring

**Comment by chriszhangusc** [comment]
I got this error too. Maybe it's because @rwieruch hasn't updated the production server for a while?

**Comment by ohadschn** [comment]
Not sure what this page displayed when this issue was first created, but here's how it looks like for me:
![image](https://user-images.githubusercontent.com/8555641/33233588-0ab2f2be-d221-11e7-9d85-d9be4f6502e6.png)

**Comment by rwieruch** [comment]
Yes. I need to update the production server. It should work on your local machine with this repository though :)

**Comment by ohadschn** [comment]
@rwieruch fair enough :)
Any plans for a deployment in the near future?

**Comment by rwieruch** [comment]
Should be fixed now. Can you check if it works for you?

FYI: As a quick fix, I just had to send all requests to the index.html file of my build folder (see https://stackoverflow.com/questions/7027636/nginx-send-all-requests-to-a-single-html-page). Didn't set it up properly when I moved to DigitalOcean.

**Comment by ohadschn** [comment]
Login works for me :)
