### ISSUE TITLE
SyntaxError: Unexpected end of JSON input in home feed infinite scroll

### ISSUE THREAD

**Issue by ohadschn** [wrobin/favesound-redux#90]
I'm sometimes getting the following error while trying to invoke infinite scroll in my home feed:

```
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at bundle.js:7
    at <anonymous>
```

![image](https://user-images.githubusercontent.com/8555641/33239600-f8fd7002-d2ad-11e7-86b3-5aba1b59ddab.png)

**Comment by rwieruch** [comment]
This would need some investigation. I never got this error myself.

**Comment by chriszhangusc** [comment]
Maybe it is a good idea to activate source-map in webpack for better debugging experience?

**Comment by rwieruch** [comment]
Didn't see this PR @MiniPekka https://github.com/rwieruch/favesound-redux/pull/81 Should I just merge it for source maps?

**Comment by chriszhangusc** [comment]
@rwieruch Yeah, I think source map would be great for development. And I also think it would be a great opportunity to upgrade to webpack 3?

**Comment by rwieruch** [comment]
Sure! Would be awesome to see it upgraded 🎉

**Comment by chriszhangusc** [comment]
@rwieruch I have upgraded to webpack3. #99

**Comment by rwieruch** [comment]
Wow. Nice @MiniPekka 🎉 🎉  I will merge it!
