### ISSUE TITLE
Add a link from the site (favesound.de) to this GitHub repository (github.com/rwieruch/favesound-redux)

### ISSUE THREAD

**Issue by ohadschn** [wrobin/favesound-redux#91]
Would be great for people who want to know more, open issues, or even contribute :)

**Comment by rwieruch** [comment]
Agreed. Let's find a sweet spot for the link :)

**Comment by ohadschn** [comment]
Well there is no "bottom" (due to infinite scrolling)... maybe just left to the login/logout link at the top right?

**Comment by ElishebaW** [comment]
@rwieruch I'll take this one!

**Comment by rwieruch** [comment]
Great @ElishebaW Do you have any good spot for it? :)

**Comment by ElishebaW** [comment]
@rwieruch I was thinking right under the logo or directly left of the logo. What do you think?

**Comment by rwieruch** [comment]
Sounds good :)

**Comment by chriszhangusc** [comment]
Merged #112
