### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by ohadschn** [wrobin/favesound-redux#93]
For a site named **fav**esound I think a nice prominent favicon would be fitting :)

![image](https://user-images.githubusercontent.com/8555641/33239720-9796f858-d2b0-11e7-8e7b-63f6c63be6d2.png)

**Comment by rwieruch** [comment]
Good idea! Can you come up with one? :)

**Comment by ohadschn** [comment]
There are many options, for example:
https://www.flaticon.com/search?word=soundcloud
https://www.iconfinder.com/search/?q=soundcloud&price=free

Most of them require attribution though, is that an issue?

**Comment by rwieruch** [comment]
I don't think so, it should be okay just mentioning it in the GitHub repo?

**Comment by ohadschn** [comment]
In the [FlatIcon case](https://file000.flaticon.com/downloads/license/license.pdf), doesn't seem so:

> For web usage: By placing a link with the text "designed by {Author's Name} from Flaticon" in a visible
> spot, so the author's authorship is noticeable

I don't think you can do it in [Creative Commons](https://wiki.creativecommons.org/wiki/Best_practices_for_attribution#Attribution_in_specific_media) either:

>  on a webpage featuring your audio recording, provide a credit list of material you used that adheres to best practices above

I am not a lawyer, but if we don't want to put an attribution on the site itself I think it may be safest to use an icon that doesn't require one. Here are some examples: http://aiconica.net/search/Soundcloud.

**Comment by Alameen007** [comment]
Hey @rwieruch, can you assign me to this?

**Comment by rwieruch** [comment]
Sure @Alameen007

**Comment by rwieruch** [comment]
Added in https://github.com/rwieruch/favesound-redux/pull/121 by @Alameen007
